
:cosgrove:
  :token: NDA0NDcwODc4ODU2ODA2NDAw.DUZsfw.4k2ihd7L5QpqqGtq2bdwesgZ2hI
  :client_id: 404470878856806400
  :secure: set this
  :operators: <pranishg>
  :upvote_weight: upvote_rules
  :upvote_rules:
    :channels:
      :default:
        :upvote_weight: 05.00 %
      :general_text:
        :channel_id: <Your Favorite Channel ID>
        :upvote_weight: 100.00 %
        :disable_comment_voting: true
:chain:
  :steem_account: 
  :steem_posting_wif: 
  :golos_account: 
  :golos_posting_wif: 
  :steem_api_url: https://api.steemit.com
  :golos_api_url: https://ws.golos.io
:discord:
  :log_mode: info
